In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/home/idies/workspace/Storage/s.hossain18/Permanent/exodata.csv').sort_index(axis=0)

In [3]:
data.head(5)

,0__has_duplicate_max,0__has_duplicate_min,0__has_duplicate,0__sum_values,0__abs_energy,0__mean_abs_change,0__mean_change,0__mean_second_derivative_central,0__median,0__mean,...,0__fourier_entropy__bins_5,0__fourier_entropy__bins_10,0__fourier_entropy__bins_100,0__permutation_entropy__dimension_3__tau_1,0__permutation_entropy__dimension_4__tau_1,0__permutation_entropy__dimension_5__tau_1,0__permutation_entropy__dimension_6__tau_1,0__permutation_entropy__dimension_7__tau_1,0__mean_n_absolute_max__number_of_maxima_7,exoplanet
0,0.0,0.0,1.0,2.064484e+08,9.087643e+13,49.472137,-1.596880,0.233340,440294.340,440188.539467,...,0.170467,0.226363,0.683850,1.731587,2.948862,4.207599,5.161319,5.692017,440732.865714,1
1,0.0,0.0,1.0,4.033714e+07,3.469264e+12,11.189566,-0.061365,0.013920,86008.328,86006.694215,...,0.589282,0.987024,3.059897,1.784421,3.140410,4.650275,5.755482,6.079708,86037.216571,1
2,0.0,0.0,1.0,2.356355e+08,1.183882e+14,31.821496,-0.043205,-0.006702,502421.660,502421.010704,...,0.822180,1.484769,3.485233,1.787237,3.155666,4.653332,5.759202,6.072590,502495.228571,1
3,0.0,0.0,1.0,1.542565e+08,5.073574e+13,20.735256,0.017564,-0.000428,328907.410,328905.047953,...,0.090729,0.136002,0.136002,1.788031,3.154802,4.640576,5.760329,6.089821,329106.067143,1
4,0.0,0.0,1.0,6.463351e+07,8.907230e+12,13.109850,0.032970,0.038822,137811.190,137811.322132,...,0.641543,1.172295,3.166886,1.791362,3.152715,4.640313,5.736220,6.063607,137844.580000,1

In [4]:
# Find columns with only 0 or 1 values
columns_to_drop = []
for column in data.columns:
    unique_values = data[column].unique()
    if len(unique_values) == 1 or (len(unique_values) == 2 and 0 in unique_values and 1 in unique_values):
        columns_to_drop.append(column)

# Drop the identified columns
df_filtered = data.drop(columns=columns_to_drop)

In [5]:
df_filtered.head(5)

,0__sum_values,0__abs_energy,0__mean_abs_change,0__mean_change,0__mean_second_derivative_central,0__median,0__mean,0__length,0__standard_deviation,0__variation_coefficient,...,0__fourier_entropy__bins_3,0__fourier_entropy__bins_5,0__fourier_entropy__bins_10,0__fourier_entropy__bins_100,0__permutation_entropy__dimension_3__tau_1,0__permutation_entropy__dimension_4__tau_1,0__permutation_entropy__dimension_5__tau_1,0__permutation_entropy__dimension_6__tau_1,0__permutation_entropy__dimension_7__tau_1,0__mean_n_absolute_max__number_of_maxima_7
0,2.064484e+08,9.087643e+13,49.472137,-1.596880,0.233340,440294.340,440188.539467,469.0,648.705379,0.001474,...,0.155665,0.170467,0.226363,0.683850,1.731587,2.948862,4.207599,5.161319,5.692017,440732.865714
1,4.033714e+07,3.469264e+12,11.189566,-0.061365,0.013920,86008.328,86006.694215,469.0,15.264155,0.000177,...,0.331889,0.589282,0.987024,3.059897,1.784421,3.140410,4.650275,5.755482,6.079708,86037.216571
2,2.356355e+08,1.183882e+14,31.821496,-0.043205,-0.006702,502421.660,502421.010704,469.0,29.967096,0.000060,...,0.451914,0.822180,1.484769,3.485233,1.787237,3.155666,4.653332,5.759202,6.072590,502495.228571
3,1.542565e+08,5.073574e+13,20.735256,0.017564,-0.000428,328907.410,328905.047953,469.0,110.932912,0.000337,...,0.045395,0.090729,0.136002,0.136002,1.788031,3.154802,4.640576,5.760329,6.089821,329106.067143
4,6.463351e+07,8.907230e+12,13.109850,0.032970,0.038822,137811.190,137811.322132,469.0,13.595516,0.000099,...,0.351390,0.641543,1.172295,3.166886,1.791362,3.152715,4.640313,5.736220,6.063607,137844.580000

In [6]:
X = df_filtered
y = data[['exoplanet']]

In [7]:
y

      exoplanet
0             1
1             1
2             1
3             1
4             1
...         ...
6765          0
6766          0
6767          0
6768          0
6769          0

[6770 rows x 1 columns]

In [26]:
# Find columns with only 0 or 1 values
columns_to_drop = []
for column in df.columns:
    unique_values = df[column].unique()
    if len(unique_values) == 1 or (len(unique_values) == 2 and 0 in unique_values and 1 in unique_values):
        columns_to_drop.append(column)

# Drop the identified columns
df_filtered = df.drop(columns=columns_to_drop)

In [28]:
df_filtered.columns

Index(['0__sum_values', '0__abs_energy', '0__mean_abs_change',
       '0__mean_change', '0__mean_second_derivative_central', '0__median',
       '0__mean', '0__length', '0__standard_deviation',
       '0__variation_coefficient',
       ...
       '0__fourier_entropy__bins_3', '0__fourier_entropy__bins_5',
       '0__fourier_entropy__bins_10', '0__fourier_entropy__bins_100',
       '0__permutation_entropy__dimension_3__tau_1',
       '0__permutation_entropy__dimension_4__tau_1',
       '0__permutation_entropy__dimension_5__tau_1',
       '0__permutation_entropy__dimension_6__tau_1',
       '0__permutation_entropy__dimension_7__tau_1',
       '0__mean_n_absolute_max__number_of_maxima_7'],
      dtype='object', length=725)

In [16]:
# Check if any column contains only 0 or 1 values
columns_to_drop = []
for column in df.columns:
    unique_values = df[column].unique()
    if len(unique_values) == 2 and set(unique_values) == {0, 1}:
        columns_to_drop.append(column)

# Print the columns containing only 0 or 1 values
if columns_to_drop:
    print("Columns to drop:")
    for column in columns_to_drop:
        print(column)
else:
    print("No columns found with only 0 or 1 values")

Columns to drop:
0__has_duplicate_max
0__has_duplicate_min
0__has_duplicate
0__symmetry_looking__r_0.05
0__symmetry_looking__r_0.1
0__symmetry_looking__r_0.15000000000000002
0__symmetry_looking__r_0.2
0__large_standard_deviation__r_0.05
0__large_standard_deviation__r_0.1
0__large_standard_deviation__r_0.15000000000000002
0__large_standard_deviation__r_0.2
0__large_standard_deviation__r_0.25
0__large_standard_deviation__r_0.30000000000000004
0__large_standard_deviation__r_0.35000000000000003
0__range_count__max_1__min_-1
exoplanet