In [1]:
import pandas as pd

In [2]:
conf = pd.read_csv('/home/idies/workspace/Storage/s.hossain18/Permanent/Data/ts_confirm.csv').sort_index(axis=0)

In [ ]:
false = pd.read_csv('/home/idies/workspace/Storage/s.hossain18/Permanent/FalsePositive/ts_falsepositive.csv').sort_index(axis=0)

In [ ]:
conf.head(5)

In [ ]:
conf.isnull().sum()

In [ ]:
false.isnull().sum().sum()

In [ ]:
columns_1 = conf.columns[conf.mean()==0]

In [ ]:
columns_1

Index(['0__symmetry_looking__r_0.0', '0__large_standard_deviation__r_0.4',
       '0__large_standard_deviation__r_0.45',
       '0__large_standard_deviation__r_0.5',
       '0__large_standard_deviation__r_0.55',
       '0__large_standard_deviation__r_0.6000000000000001',
       '0__large_standard_deviation__r_0.65',
       '0__large_standard_deviation__r_0.7000000000000001',
       '0__large_standard_deviation__r_0.75',
       '0__large_standard_deviation__r_0.8',
       ...
       '60__value_count__value_0', '60__value_count__value_1',
       '60__value_count__value_-1', '60__range_count__max_1__min_-1',
       '60__range_count__max_0__min_-1000000000000.0',
       '60__number_crossing_m__m_0', '60__number_crossing_m__m_-1',
       '60__number_crossing_m__m_1', '60__count_below__t_0',
       '60__query_similarity_count__query_None__threshold_0.0'],
      dtype='object', length=1862)

In [ ]:
conf['exoplanet'] = 1

In [ ]:
conf.head(5)

,0__variance_larger_than_standard_deviation,0__has_duplicate_max,0__has_duplicate_min,0__has_duplicate,0__sum_values,0__abs_energy,0__mean_abs_change,0__mean_change,0__mean_second_derivative_central,0__median,...,60__fourier_entropy__bins_10,60__fourier_entropy__bins_100,60__permutation_entropy__dimension_3__tau_1,60__permutation_entropy__dimension_4__tau_1,60__permutation_entropy__dimension_5__tau_1,60__permutation_entropy__dimension_6__tau_1,60__permutation_entropy__dimension_7__tau_1,60__query_similarity_count__query_None__threshold_0.0,60__mean_n_absolute_max__number_of_maxima_7,exoplanet
0,1.0,0.0,0.0,1.0,2.064484e+08,9.087643e+13,49.472137,-1.596880,0.233340,440294.340,...,0.136002,0.495840,1.791743,3.177742,4.786038,6.572025,8.474889,0.0,410189.544286,1
1,1.0,0.0,0.0,1.0,4.033714e+07,3.469264e+12,11.189566,-0.061365,0.013920,86008.328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,1.0,0.0,0.0,1.0,2.356355e+08,1.183882e+14,31.821496,-0.043205,-0.006702,502421.660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,1.0,0.0,0.0,1.0,1.542565e+08,5.073574e+13,20.735256,0.017564,-0.000428,328907.410,...,0.839608,2.308983,1.791289,3.175183,4.775757,6.517038,8.052126,0.0,331460.540000,1
4,1.0,0.0,0.0,1.0,6.463351e+07,8.907230e+12,13.109850,0.032970,0.038822,137811.190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [ ]:
false['exoplanet'] = 0

In [ ]:
false.head(5)

,16__variance_larger_than_standard_deviation,16__has_duplicate_max,16__has_duplicate_min,16__has_duplicate,16__sum_values,16__abs_energy,16__mean_abs_change,16__mean_change,16__mean_second_derivative_central,16__median,...,57__fourier_entropy__bins_10,57__fourier_entropy__bins_100,57__permutation_entropy__dimension_3__tau_1,57__permutation_entropy__dimension_4__tau_1,57__permutation_entropy__dimension_5__tau_1,57__permutation_entropy__dimension_6__tau_1,57__permutation_entropy__dimension_7__tau_1,57__query_similarity_count__query_None__threshold_0.0,57__mean_n_absolute_max__number_of_maxima_7,exoplanet
0,1.0,0.0,0.0,1.0,1.568351e+07,1.916345e+11,17.367199,-0.125146,-0.004549,12241.5195,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1.0,0.0,0.0,1.0,8.933664e+06,6.218434e+10,6.303739,0.032980,-0.001100,6950.7295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1.0,0.0,0.0,1.0,1.175309e+09,3.908793e+14,24.888070,0.319958,0.000760,332682.6100,...,0.974579,2.920229,1.791747,3.177862,4.786547,6.573132,8.478,0.0,334965.25,0
3,1.0,0.0,0.0,1.0,2.462977e+09,1.720793e+15,4673.841656,-18.946343,4.423802,710195.2500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1.0,0.0,0.0,1.0,7.133205e+08,1.438581e+14,226.131578,-0.190215,0.037154,202007.3500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
df = pd.concat([conf,false],ignore_index=True, sort=False)

In [ ]:
df.head(5)

,0__variance_larger_than_standard_deviation,0__has_duplicate_max,0__has_duplicate_min,0__has_duplicate,0__sum_values,0__abs_energy,0__mean_abs_change,0__mean_change,0__mean_second_derivative_central,0__median,...,60__fourier_entropy__bins_10,60__fourier_entropy__bins_100,60__permutation_entropy__dimension_3__tau_1,60__permutation_entropy__dimension_4__tau_1,60__permutation_entropy__dimension_5__tau_1,60__permutation_entropy__dimension_6__tau_1,60__permutation_entropy__dimension_7__tau_1,60__query_similarity_count__query_None__threshold_0.0,60__mean_n_absolute_max__number_of_maxima_7,exoplanet
0,1.0,0.0,0.0,1.0,2.064484e+08,9.087643e+13,49.472137,-1.596880,0.233340,440294.340,...,0.136002,0.495840,1.791743,3.177742,4.786038,6.572025,8.474889,0.0,410189.544286,1
1,1.0,0.0,0.0,1.0,4.033714e+07,3.469264e+12,11.189566,-0.061365,0.013920,86008.328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,1.0,0.0,0.0,1.0,2.356355e+08,1.183882e+14,31.821496,-0.043205,-0.006702,502421.660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,1.0,0.0,0.0,1.0,1.542565e+08,5.073574e+13,20.735256,0.017564,-0.000428,328907.410,...,0.839608,2.308983,1.791289,3.175183,4.775757,6.517038,8.052126,0.0,331460.540000,1
4,1.0,0.0,0.0,1.0,6.463351e+07,8.907230e+12,13.109850,0.032970,0.038822,137811.190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [ ]:
columns_1 = df.columns[df.mean()==1]

In [ ]:
columns_2 = df.columns[df.mean()==0]

In [ ]:
 df = df.drop(columns=columns_1)

In [ ]:
df = df.drop(columns=columns_2)

In [1]:
df = df.dropna(axis=1)

NameError: ignored

In [ ]:
# saving the dataframe
df.to_csv('/home/idies/workspace/Storage/s.hossain18/Permanent/exodata.csv', index=False)